### PR TITLE
#160831446 Add the REST-API endpoints for adding an order, viewing a specific order, viewing all orders and updating a particular order status

### PR DESCRIPTION
**Pull request by kdaglas**
### What does this PR do?
This PR adds the following API endpoints:
the endpoint for placing an order
the endpoint for viewing a particular order
the endpoint for viewing all orders
the endpoint for updating the status of a particular order

#### Description of Task to be completed:
have the following endpoints to be functional:
```POST /api/v1/orders```
```GET /api/v1/orders```
```GET /api/v1/orders/<orderId>```
```PUT /api/v1/orders/<orderId>```

#### How should this be manually tested?
Go to the README.md to access a well-elaborated way to test the application

#### Relevant pivotal tracker stories?
#160481675
#160483567
#160489184
#160491074

#### Screenshots (if appropriate)
GET view all orders request
getall
GET view one order request
getone
POST place an order request
place
PUT update an order status
putmthd

### CODE REVIEW

**Comment by Sebuliba-Adrian** [comment]
Good work @kdaglas . However you need to resolve conflicts before you can merge

**Comment by nanfuka** [comment]
i like the detail in your pull request. great work

**Comment by d-rita** [comment]
Standard PR. Good work

**Comment by billkabanga** [comment]
Good work with the standard git workflow.

**Comment by kdaglas** [comment]
Thank you guys

**Comment by kdaglas** [comment]
@Sebuliba-Adrian the conflicts are fixed... am now merging

**Pull request merged**
