### PR TITLE
#160767818 Add comments to the API end points functionality and the tests for the APIs

### PR DESCRIPTION
**Pull request by kdaglas**
### What does this PR do?
This PR is doing the following:
- Add doc strings comments to the API code for the POST, GET and PUT methods
- Add the doc string documentation to the validation for the endpoints
- Add comments in form of doc strings to the tests of the APIs

#### Description of Task to be completed:
- Provide an elaborative description for the functionality of the code
- Provide information about snippets of code that are carrying out different functionality

#### How should this be manually tested?
Go to the README.md to access a well-elaborated way to test the application

#### Relevant pivotal tracker stories?
#160767818
#160790663
#160790849

#### Screenshots (if appropriate)
capture12
capture13

#### Questions:
if any please comment in the comments section

### CODE REVIEW

**Comment by billkabanga** [comment]
I like the fact that you have applied docstrings to your code. Good test coverage and it's good you have a validation class. 
Then personally I would prefer to have the docstring inside its method or function
Something like this
 `def __init__():`
        `''' constructor....... '''`

**Comment by nanfuka** [comment]
great. correction done

**Comment by aayebare** [comment]
nice work. Maybe you could remove the redundant blank lines where not necessary to make the code neat

**Comment by d-rita** [comment]
Good implementation of docstrings. Just a few spacing errors within tho.

**Comment by aayebare** [comment]
nice work. Maybe you could remove the redundant blank lines between code if not necessary. Would make it neat

**Comment by kdaglas** [comment]
ok thanks let me work on your feedback

**Comment by aayebare** [comment]
very descriptive ... I'm at peace

**Comment by billkabanga** [comment]
Good work

**Comment by d-rita** [comment]
Good work!

**Comment by nanfuka** [comment]
@kdaglas well edited. you have explained your functions well in your docstrings

**Comment by nanfuka** [comment]
if this is how all of you functions are commented, then i think this is satisfactory

**Pull request closed without merging**
